on:
  pull_request:
    branches:
      - '**'

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Try to get diff
    outputs:
      changed-packages: ${{ steps.changes.outputs.packages }}
      changed-array: ${{ steps.changes.outputs.packagesArray }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          cache: npm
          node-version: latest
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build actions
        run: npm run build --workspace=@puppeteer/actions
      - name: Get Diff Step
        id: changes
        uses: ./actions/changed-packages

  get-from-step:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ contains( fromJSON(needs.changes.outputs.changed-array), 'public' ) }}
    name: Can it get data
    steps:
      - name: Get if public was changed
        run: echo "It works"