on:
  pull_request:
    branches:
      - '**'

jobs:
  get-diff:
    runs-on: ubuntu-latest
    name: Try to get diff
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get Diff Step
        id: diff
        uses: ./actions/get-diff
      - name: Get if public was changed
        run: echo "Public was ${{ steps.diff.outputs.public }}"
      - name: Get if puppeteer has changed
        run: echo "Puppeteer was ${{ steps.diff.outputs.puppeteer }}"
      - name: Get if puppeteer-core has changed
        run: echo "Puppeteer was ${{ steps.diff.outputs.puppeteer-core }}"