on:
  pull_request:
    branches:
      - '**'

jobs:
  get-diff:
    runs-on: ubuntu-latest
    name: Try to get diff
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          cache: npm
          node-version: latest
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build actions
        run: npm run actions
      - name: Get Diff Step
        id: diff
        uses: ./actions/get-diff

  get-from-step:
    runs-on: ubuntu-latest
    needs: get-diff
    if: ${{ needs.get-diff.outputs.public == 'true' }}
    name: Can it get data
    steps:
      - name: Get if public was changed
        run: echo "It works"